### ISSUE TITLE
Re-instantiate blobs if we run into 404 issues

### ISSUE THREAD

**Issue by dandhlee** [googleapis/doc-pipeline#106]
@cojenco helped looked into the issue where if by the time the `Blob` is instantiated and when we download tarballs inside the `Blob` using `blob.download_to_filename()`, it could fail if there is a "newer" version of the file that's re-uploaded. There is a `generation` parameter that gets included by default for the storage query. This can be avoided by re-instantiating the Blob if we run into a 404, which should minimize the amount of times we could fail with 404s.

**Comment by tbpg** [comment]
Closing this for now as it hasn't come up in a while.

**Comment by dandhlee** [comment]
Ran into this problem again in #182, still very infrequent. Will re-open and investigate if we run into this problem again.

**Comment by tbpg** [comment]
Reopening because this has come up again recently. I'll take a try at fixing it.
