### ISSUE TITLE
Automatically rebuild HTML when templates or YAML update

### ISSUE THREAD

**Issue by tbpg** [googleapis/doc-pipeline#66]
Right now, if you update the templates or the YAML of a package, the HTML won't get regenerated automatically. What if our default job changed to:

1. Get all blobs.
2. For every YAML blob:
    1. If no HTML version exists, generate it.
    2. Else if an HTML version exists and it was updated _before_ the YAML blob, regenerate it.
    3. Else if an HTML version exists and it was generated _before_ the latest commit to doc-templates, regenerate it.

**Comment by tbpg** [comment]
Sometimes, it's nice to batch changes into regeneration runs. If we submit 1 CL per day for a week, no need to regenerate everything until the end of the week. If we automatically regenerate, it could lead to more churn than necessary.

**Comment by tbpg** [comment]
One way to avoid the churn caused by doc-templates would be to just... not look at doc-templates. So, we'd get rid of 2.iii in the logic above.

That would give library owners a good experience when they update the YAML. It would also allow us to batch changes to the templates.

**Comment by dandhlee** [comment]
The scope for now will be limited for 2.i (current behavior) and 2.ii. It will compare the YAML blob's time with the HTML blob's time to check and re-generate if possible.
