### ISSUE TITLE
docfx: Go xrefmap files breaking build

### ISSUE THREAD

**Issue by tbpg** [googleapis/doc-pipeline#68]
```
docpipeline > [Errno 2] No such file or directory: '/workspace/xrefs/go-cloud.google.com/go-v0.75.0.tar.gz.yml'
```

**Comment by tbpg** [comment]
cc @dandhlee @eaball35 @fhinkel @jskeet

**Comment by jskeet** [comment]
Hmm... I thought docfx ignored xref map files it can't find. Maybe it does that for URIs but not files? Although for files, we should have everything anyway...

Perhaps the problem here is the filename? An extension of ".tar.gz.yml" looks a little odd...

**Comment by tbpg** [comment]
The problem is in Python -- the Storage client's `download_to_filename` fails if the necessary directories don't exist.

I chose that filename for the downloaded files to make it very easy to go from source blob to the xrefmap file for that blob -- just add `.yml`.
