### ISSUE TITLE
Only fetch the exact xrefmap files needed for the current build

### ISSUE THREAD

**Issue by tbpg** [googleapis/doc-pipeline#70]
Tarballs can specify the xrefmaps they need using the `xrefs` field in `docs.metadata`. Let's use that field to specify the exact xrefmap files needed for the current build, rather than downloading _every_ xrefmap for _every_ build.

@jskeet came up with:
```
devsite://dotnet/Google.Api.Gax/2.5.0
```

We can convert that to an xrefmap by removing `devsite://`, replacing the first and last `/` with `-`, and adding `.tar.gz.yml` at the end. It will be an error if that xrefmap does not exist.

Another benefit of this is that one library can have multiple versions. Each version will have its own xrefmap. If _every_ xrefmap is pulled in, there will be multiple `xrefmap` files that register the same UIDs. Plus, when we support multiple versions, we'll need to use just the right version of the xrefmap as URLs will be different.

Finally, this will benefit libraries without xrefs because they won't need to download anything.

@jskeet will implement the change to the dotnet libraries. I will implement the change to doc-pipeline.

**Comment by jskeet** [comment]
Slight suggested change: 

- Specific version: `devsite://dotnet/Google.Api.Gax@2.5.0`
- Latest version: `devsite://dotnet/Google.Api.Gax`

(We may not *easily* know the specific version of the dependency when generating the list.)

Does that make things significantly harder in the pipeline?

**Comment by jskeet** [comment]
(I'm guessing it does in terms of knowing which blobs to download. Hmm.)

**Comment by tbpg** [comment]
We could make it work in the pipeline -- we can get the names of all of the blobs with the right prefix, sort them by SemVer (:fearful:), and download the latest one.

**Comment by jskeet** [comment]
Great - I'll assume the format in https://github.com/googleapis/doc-pipeline/issues/70#issuecomment-782149248 then when writing the .NET side of things.
